DurabilityWoodenExcavator=59
DurabilityStoneExcavator=131
DurabilityIronExcavator=250
DurabilityGoldExcavator=32
DurabilityLapisExcavator=280
DurabilityRedstoneExcavator=290
DurabilityObsidianExcavator=1500
DurabilityDiamondExcavator=1561
DurabilityEmeraldExcavator=1700
DurabilityNetheriteExcavator=2031
DurabilityWoodenHammer=59
DurabilityStoneHammer=131
DurabilityIronHammer=250
DurabilityGoldHammer=32
DurabilityLapisHammer=280
DurabilityRedstoneHammer=290
DurabilityObsidianHammer=1500
DurabilityDiamondHammer=1561
DurabilityEmeraldHammer=1700
DurabilityNetheriteHammer=2031