name = "the-solar-apocalypse"
author = "SeriousFreezing"
version = "22.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb57678cd3409294af071a4faab49d6b9f1f9de511d07baa7cf23b4512ae7fa8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = ["1.21.1"]
