name = "SolarApocalypse"
author = "SeriousFreezing"
version = "17.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace4f0e34a65abb1f69601100b29915e069a1a8e58d66aa9cd5cae78e39ed4a0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.1"]
