name = "The Solar Apocalypse"
author = "SeriousFreezing"
version = "16.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d90d3c6d806e24868388e40248b9b029dadc651c71ad7d5878bac513b8af0eb0"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
