name = "SolarApocalypse"
author = "SeriousFreezing"
version = "21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40a649c8a8a1482840a9c3ac1c1193f07285927c972f2ea967919c626c1113df"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21", "1.20.1"]
